### ISSUE TITLE
Different Eprints config file?

### ISSUE THREAD

**Issue by adam-rehin** [jisc-services/eprints-plugin-PubRouter-RIOXXplus-Connector#8]
Looking at Eprints-Hosting installation of new plugin, in http://jisc-rioxx.eprints-hosting.org/cgi/users/home?screen=Admin%3A%3AConfig I see there are now 2 config files:

* zzz_pubrouter_import.pl - http://jisc-rioxx.eprints-hosting.org/cgi/users/home?screen=Admin%3A%3AConfig%3A%3AView%3A%3APerl&configfile=cfg.d%2Fzzz_pubrouter_import.pl
* zzz_pubrouter_rioxx_importer.pl - http://jisc-rioxx.eprints-hosting.org/cgi/users/home?screen=Admin%3A%3AConfig%3A%3AView%3A%3APerl&configfile=cfg.d%2Fzzz_pubrouter_rioxx_importer.pl

Did the filename change with the new version of the plugin?  Which is the new config file?
Did it have to? It would be better if the new plugin used the original config file to avoid having to re-enter config values.
If a differently named config file is necessary then the documentation will need to be updated (I recollect that I can do that).

**Comment by wfyson** [comment]
The file zzz_pubrouter_import.pl is not used and I'm not sure how it got there. I suspect it may be a very old version of the file, before we settled on calling it zzz_pubrouter_rioxx_importer.pl instead. It's not included as part of the Bazaar package or in this GitHub repository and so is nothing to worry about.
